esphome:
  name: curtainmotor_test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi
  password: !secret wifi_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: gpio
    id: 'shade_open'
    pin: D1
  - platform: gpio
    id: 'shade_close'
    pin: D2

switch:
  - platform: output
    name: "shade_open"
    internal: true
    output: 'shade_open'
    id: shade_s1
  - platform: output
    name: "shade_close"
    internal: true
    output: 'shade_close'
    id: shade_s2

binary_sensor:
#open
  - platform: gpio
    pin: 
        number: D3
    id: 'button_up'
    internal: true
    filters:
      invert:
    on_press:
        then:
          if:
            condition:
              binary_sensor.is_on: limit_up
            then:
              - switch.turn_off: shade_s1
            else:
              - switch.turn_on: shade_s1

#close
  - platform: gpio
    pin: 
        number: D4
    id: 'button_down'
    internal: true
    filters:
      invert:
    on_press:
        then:
          if:
            condition:
              - binary_sensor.is_on: limit_down
            then:
              - switch.turn_off: shade_s2
            else:
              - switch.turn_on: shade_s2

    on_release:
        then:
            - switch.turn_off: shade_s2

#limit up
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
    name: 'limit_up'
    id: 'limit_up'
    internal: true
    filters:
      invert:
    on_press:
     then:
       - switch.turn_off: shade_s1
       - cover.template.publish:
          id: kitchen_window
          state: OPEN


#limit down
  - platform: gpio
    pin: 
      number: D6
      mode: INPUT_PULLUP
    name: 'limit_down'
    id: 'limit_down'
    internal: true
    filters:
      invert:
    on_press:
     then:
       - switch.turn_off: shade_s2
       - cover.template.publish:
          id: kitchen_window
          state: CLOSED

cover:
  - platform: template
    name: "Kitchen Window Full"
    id: kitchen_window
    optimistic: true
    open_action:
      if:
        condition:
          - binary_sensor.is_on: limit_up
        then:
          - switch.turn_off: shade_s1
        else:
          - switch.turn_off: shade_s2
          - switch.turn_on: shade_s1
    close_action:
      if:
        condition:
          - binary_sensor.is_on: limit_down
        then:
          - switch.turn_off: shade_s2
        else:
          - switch.turn_off: shade_s1
          - switch.turn_on: shade_s2
    stop_action:
      - switch.turn_off: shade_s1
      - switch.turn_off: shade_s2
      
  - platform: template
    name: "Kitchen Window Control"
    id: kitchen_control
    assumed_state: true
    open_action:
      if:
        condition:
          - binary_sensor.is_on: limit_up
        then:
          - switch.turn_off: shade_s1
        else:
          - switch.turn_off: shade_s2
          - switch.turn_on: shade_s1
    close_action:
      if:
        condition:
          - binary_sensor.is_on: limit_down
        then:
          - switch.turn_off: shade_s2
        else:
          - switch.turn_off: shade_s1
          - switch.turn_on: shade_s2
    stop_action:
      - switch.turn_off: shade_s1
      - switch.turn_off: shade_s2
