esphome:
  name: **change me**
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "**change me**"
    password: !secret wifi_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
    id: button
    on_press:
      - switch.toggle: relay


switch:
  - platform: gpio
    id: red_led
    inverted: true
    pin: GPIO12

  - platform: gpio
    name: "**change me**"
    pin: GPIO5
    inverted: true
    id: relay
    
    on_turn_on:
      - switch.turn_off: red_led

    on_turn_off:
      - switch.turn_on: red_led
