binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
    id: button
    on_press:
      - switch.toggle: relay


switch:
  - platform: gpio
    id: red_led
    inverted: true
    pin: GPIO12

  - platform: gpio
    name: "Bathroom Dehumidifier"
    pin: GPIO5
    inverted: true
    id: relay
    
    on_turn_on:
      - switch.turn_off: red_led

    on_turn_off:
      - switch.turn_on: red_led
