esphome:
  name: **change me**
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "**change me** Fallback Hotspot"
    password: !secret wifi_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
dallas:
  - pin: GPIO03

# Individual sensors
sensor:
  - platform: dallas
    index : 0
    name: "**change me**"
    id: **change me**_temp

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: led
    pin: GPIO13
    inverted: true
    
  - platform: gpio
    name: "**change me** Control"
    pin: GPIO12
    id: relay

    on_turn_off:
      - switch.turn_off: led

    on_turn_on:
      - switch.turn_on: led
